name: Amazon Playwright Tests using Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v3.1.4
      with:
        python-version: '3.1.4'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        source /Volumes/EXT - HDD/Deadliest/Automation/PlayWright/Amazon
